### ISSUE TITLE
LICENSE Concern

### ISSUE THREAD

**Issue by tenthirtyam** [DonBower/packer-vsphere-ubuntu#69]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Project Version

main

### VMware vSphere

-

### HashiCorp Packer

-

### HashiCorp Packer Plugin for VMware vSphere

-

### Guest Operating System

-

### Environment Details

-

### Description

This public project comprises copies much of the code from [`vmware-samples/packer-examples-for-vsphere`](https://github.com/vmware-samples/packer-examples-for-vsphere) but removes the `LICENSE` file, which is in violation of the BSD-2 license.

https://github.com/vmware-samples/packer-examples-for-vsphere/blob/develop/LICENSE

### Expected Behavior

Adhere to the source license.

### Actual Behavior

Does not adhere to the source license.

### Steps to Reproduce

Code review.

**Comment by DonBower** [comment]
just to be clear, is this because the LICENSE file that is in the REPO is GNU-GPL, and not BSD-2?

**Comment by tenthirtyam** [comment]
Take a look at the statement in the originating LICENSE. It has the requirements and the copywrite must be maintained.

**Comment by DonBower** [comment]
is it acceptable to add the line:
`Portions modified by Don Bower.`

**Comment by tenthirtyam** [comment]
I'll check with our OSS team and let you know.

**Comment by tenthirtyam** [comment]
From our open source team: 

> _"The BSD-2 license that applies to all parts of the project packer-examples-for-vsphere states that you may use this file in compliance with the BSD-2 license and its 2 conditions."_

**Comment by tenthirtyam** [comment]
Any update?

**Comment by tenthirtyam** [comment]
Thank you!
